// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANU2Wywt9ZrjLv7rnmCShhsudiyrdpkFg',
    appId: '1:176747950072:web:a4c14263255a338705b00d',
    messagingSenderId: '176747950072',
    projectId: 'flutter-login-riverpod',
    authDomain: 'flutter-login-riverpod.firebaseapp.com',
    storageBucket: 'flutter-login-riverpod.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCPX1LGdyhdoUvzg02q9jKloTsa5XBgFE',
    appId: '1:176747950072:android:4b63a7f3b718c4f305b00d',
    messagingSenderId: '176747950072',
    projectId: 'flutter-login-riverpod',
    storageBucket: 'flutter-login-riverpod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpFcvp0uwyZuGKlhr-7u8sPIFnUQQpzhE',
    appId: '1:176747950072:ios:342ab9da59098cf005b00d',
    messagingSenderId: '176747950072',
    projectId: 'flutter-login-riverpod',
    storageBucket: 'flutter-login-riverpod.firebasestorage.app',
    iosBundleId: 'com.example.flutterLoginRiverpod',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpFcvp0uwyZuGKlhr-7u8sPIFnUQQpzhE',
    appId: '1:176747950072:ios:342ab9da59098cf005b00d',
    messagingSenderId: '176747950072',
    projectId: 'flutter-login-riverpod',
    storageBucket: 'flutter-login-riverpod.firebasestorage.app',
    iosBundleId: 'com.example.flutterLoginRiverpod',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANU2Wywt9ZrjLv7rnmCShhsudiyrdpkFg',
    appId: '1:176747950072:web:c9634eb1d2bb8fa105b00d',
    messagingSenderId: '176747950072',
    projectId: 'flutter-login-riverpod',
    authDomain: 'flutter-login-riverpod.firebaseapp.com',
    storageBucket: 'flutter-login-riverpod.firebasestorage.app',
  );
}
